import type { StudioModelDefinition } from "./types";

export const STUDIO_MODEL_CATALOG: StudioModelDefinition[] = [
  {
    id: "nano-banana-2",
    name: "Nano Banana 2",
    providerLabel: "Fal",
    kind: "image",
    section: "images",
    description: "Fast image generation with clean compositions and reference support.",
    heroGradient:
      "from-orange-400/25 via-amber-300/10 to-transparent",
    tags: ["Image", "Fast", "Reference-ready"],
    promptPlaceholder:
      "Describe the image you want to create, including mood, framing, subject, and style.",
    supportsNegativePrompt: false,
    supportsReferences: true,
    aspectRatioOptions: ["1:1", "4:5", "3:4", "16:9", "9:16"],
    resolutionOptions: ["1024", "1536", "2048"],
    imageCountOptions: [1, 2, 4],
    defaultDraft: {
      prompt: "",
      negativePrompt: "",
      aspectRatio: "1:1",
      resolution: "1536",
      imageCount: 1,
      durationSeconds: 8,
      includeAudio: true,
      tone: "Balanced",
      maxTokens: 1024,
      temperature: 0.7,
    },
  },
  {
    id: "flux-pro",
    name: "Flux Pro",
    providerLabel: "Fal",
    kind: "image",
    section: "images",
    description: "Sharper visual detail for polished stills and prompt-driven exploration.",
    heroGradient: "from-fuchsia-400/25 via-pink-300/10 to-transparent",
    tags: ["Image", "Detail", "Creative"],
    promptPlaceholder:
      "Describe the still image, design language, materials, lighting, and camera feel.",
    supportsNegativePrompt: true,
    supportsReferences: true,
    aspectRatioOptions: ["1:1", "4:5", "3:2", "16:9", "9:16"],
    resolutionOptions: ["1024", "1536", "2048"],
    imageCountOptions: [1, 2],
    defaultDraft: {
      prompt: "",
      negativePrompt: "",
      aspectRatio: "4:5",
      resolution: "1536",
      imageCount: 1,
      durationSeconds: 8,
      includeAudio: true,
      tone: "Balanced",
      maxTokens: 1024,
      temperature: 0.7,
    },
  },
  {
    id: "veo-3.1",
    name: "Veo 3.1",
    providerLabel: "Fal",
    kind: "video",
    section: "videos",
    description: "Narrative video generation with strong motion language and reference support.",
    heroGradient: "from-sky-400/25 via-cyan-300/10 to-transparent",
    tags: ["Video", "Narrative", "Audio"],
    promptPlaceholder:
      "Describe the motion, camera movement, subject behavior, lighting, and pacing.",
    supportsNegativePrompt: true,
    supportsReferences: true,
    aspectRatioOptions: ["16:9", "9:16", "1:1"],
    resolutionOptions: ["720p", "1080p"],
    durationOptions: [5, 8, 10],
    defaultDraft: {
      prompt: "",
      negativePrompt: "",
      aspectRatio: "16:9",
      resolution: "1080p",
      imageCount: 1,
      durationSeconds: 8,
      includeAudio: true,
      tone: "Balanced",
      maxTokens: 1024,
      temperature: 0.7,
    },
  },
  {
    id: "kling-2.1",
    name: "Kling 2.1",
    providerLabel: "Fal",
    kind: "video",
    section: "videos",
    description: "Stylized motion generation for fast concepting and short-form visual tests.",
    heroGradient: "from-emerald-400/25 via-teal-300/10 to-transparent",
    tags: ["Video", "Stylized", "Short-form"],
    promptPlaceholder:
      "Describe the scene, movement, visual treatment, transitions, and subject energy.",
    supportsNegativePrompt: false,
    supportsReferences: true,
    aspectRatioOptions: ["16:9", "9:16", "1:1"],
    resolutionOptions: ["720p", "1080p"],
    durationOptions: [5, 8],
    defaultDraft: {
      prompt: "",
      negativePrompt: "",
      aspectRatio: "9:16",
      resolution: "720p",
      imageCount: 1,
      durationSeconds: 5,
      includeAudio: false,
      tone: "Balanced",
      maxTokens: 1024,
      temperature: 0.7,
    },
  },
  {
    id: "llm-router-gpt4-mini",
    name: "GPT-4.1 Mini",
    providerLabel: "Fal via OpenRouter",
    kind: "text",
    section: "text",
    description: "Fast general-purpose writing, ideation, rewriting, and prompt development.",
    heroGradient: "from-violet-400/25 via-purple-300/10 to-transparent",
    tags: ["Text", "Fast", "General"],
    promptPlaceholder:
      "Ask for a script, rewrite, shot list, creative brief, prompt pack, or structured plan.",
    supportsNegativePrompt: false,
    supportsReferences: false,
    toneOptions: ["Balanced", "Direct", "Cinematic", "Playful"],
    maxTokenOptions: [512, 1024, 2048, 4096],
    defaultDraft: {
      prompt: "",
      negativePrompt: "",
      aspectRatio: "1:1",
      resolution: "1536",
      imageCount: 1,
      durationSeconds: 8,
      includeAudio: true,
      tone: "Balanced",
      maxTokens: 2048,
      temperature: 0.7,
    },
  },
  {
    id: "llm-router-gemini-flash",
    name: "Gemini 2.5 Flash",
    providerLabel: "Fal via OpenRouter",
    kind: "text",
    section: "text",
    description: "Quick drafting, iteration, and idea expansion inside the same studio.",
    heroGradient: "from-indigo-400/25 via-blue-300/10 to-transparent",
    tags: ["Text", "Responsive", "Drafting"],
    promptPlaceholder:
      "Outline a campaign, rewrite copy, draft a script, or refine a prompt for image or video generation.",
    supportsNegativePrompt: false,
    supportsReferences: false,
    toneOptions: ["Balanced", "Analytical", "Friendly", "Punchy"],
    maxTokenOptions: [512, 1024, 2048, 4096],
    defaultDraft: {
      prompt: "",
      negativePrompt: "",
      aspectRatio: "1:1",
      resolution: "1536",
      imageCount: 1,
      durationSeconds: 8,
      includeAudio: true,
      tone: "Analytical",
      maxTokens: 2048,
      temperature: 0.6,
    },
  },
];

export const STUDIO_MODEL_SECTIONS = [
  {
    id: "images",
    title: "Images",
    description: "Still image generation models",
  },
  {
    id: "videos",
    title: "Videos",
    description: "Motion generation models",
  },
  {
    id: "text",
    title: "Text",
    description: "Fal-routed LLMs",
  },
] as const;

export function getStudioModelById(modelId: string) {
  return (
    STUDIO_MODEL_CATALOG.find((model) => model.id === modelId) ??
    STUDIO_MODEL_CATALOG[0]
  );
}
